
backend = "glx";

# Blur
blur = true;
blur-method = "dual_kawase";
blur-strength = 3;

# Corner radius
corner-radius = 15;

rules = (
    # Sem bordas arredondadas para barra e menus
    {
        match = "class_g = 'Polybar' || class_g = 'dmenu' || class_g = 'rofi' || class_g = 'i3lock'";
        corner-radius = 0;
    },
    # Opacity
    {
        match = "class_g = 'vivaldi-stable'";
        opacity = 1.0;
    },
    {
        match = "class_g = 'Alacritty' && focused";
        opacity = 1.0;
    },
    {
        match = "class_g = 'Alacritty' && !focused";
        opacity = 0.85;
    },
    {
        match = "class_g = 'kitty' && focused";
        opacity = 0.95;
    },
    {
        match = "class_g = 'kitty' && !focused";
        opacity = 0.78;
    }
);

# === ANIMAÇÕES ===

