
[colors]
background = #282A2E
background-alt = #373B41
foreground = #C5C8C6
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880

[bar/main-secondary]
monitor = ${env:MONITOR}
width = 100%
height = 32
radius = 6

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

#font-0 = monospace;2
font-0 = "JetBrainsMono Nerd Font:size=11;2"

modules-left = cpu filesystem
modules-center = date
modules-right =  xkeyboard bluetooth wlan eth

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true


; wm-restack = generic
; wm-restack = bspwm
 wm-restack = i3

 override-redirect = false


[module/bluetooth]
type = custom/script
#exec = bluethoothctl show | grep "Powed: yes" >/dev/null && echo " BT" || echo " off"
exec = bluetoothctl show | grep "Powered: yes" >/dev/null && echo "" || echo " off"
interval = 3
click-left = blueman-manager

[module/filesystem]
type = internal/fs
interval = 25

#mount-0 = /

label-mounted =  %{F#F0C674}%used%/%total%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/cpu]
type = custom/script
exec = awk '{printf " CPU %.1f°C\n", $1/1000}' /sys/class/hwmon/hwmon1/temp1_input
interval = 2
click-left = alacritty --title btop -e btop

[network-base]
type = internal/network
interval = 5
label-connected = %{F#A6E3A1}%{F-}
label-disconnected = %{F#F38BA8}󰖪%{F-}
#label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
#label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
#label-connected = %{F#F0C674}%ifname%%{F-}

[module/date]
type = internal/date
interval = 1

locale = pt_BR.UTF-8

date = %a %H:%M
date-alt = %A, %d/%m/%Y - %H:%M:%S

label = %date%
label-foreground = ${colors.primary}




[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
